subscribe:
  path: /subscribe
  controller: App\Controller\SubscriptionsController::create
  methods: OPTIONS|POST

stats:
  path: /stats
  controller: App\Controller\SubscriptionsController::statistics
  methods: OPTIONS|GET